version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    container_name: rabbitmq-container
    ports:
      - "5672:5672"
      - "15672:15672"

  consumer:
    container_name: notifications-service
    build: ./notifications_service
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_QUEUE=product_events